services:
  - type: web
    name: skinsense-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ORIGINS
        value: "https://skinsense.netlify.app,http://localhost:3000,http://localhost:5173"
    healthCheckPath: /health

